version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "to-timestream"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19l7e0fs5gjid"
s3_prefix = "to-timestream"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
