AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  qiita_f52c0841775f9fc4d0c5_owntracks

  Sample SAM Template for qiita_f52c0841775f9fc4d0c5_owntracks

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Qiitaf52c0841775f9fc4d0c5OwntracksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: qiita_f52c0841775f9fc4d0c5_owntracks/
      Handler: app.lambda_handler
      Runtime: python3.7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Qiitaf52c0841775f9fc4d0c5OwntracksFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt Qiitaf52c0841775f9fc4d0c5OwntracksFunction.Arn
  Qiitaf52c0841775f9fc4d0c5OwntracksFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt Qiitaf52c0841775f9fc4d0c5OwntracksFunctionIamRole.Arn
